# Generated by Django 5.1.7 on 2025-03-23 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_watcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watcher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='watcher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
